import type { Track } from "./types.ts";

const P = {
  playable: "playable",
  blocked: "embedding_disabled",
  gone: "unavailable",
} as const;

export const MOCK_TRACKS: Track[] = [
  {
    id: "ntrk_copper_hours",
    title: "Copper Hours",
    channel: "North Room",
    durationSec: 214,
    hue: 28,
    pattern: "vinyl",
    status: P.playable,
    description: "Warm low end, late-desk tempo.",
  },
  {
    id: "ntrk_late_atlas",
    title: "Late Atlas",
    channel: "Harbor Line",
    durationSec: 187,
    hue: 210,
    pattern: "arcs",
    status: P.playable,
    description: "Coastal night drive, measured pulse.",
  },
  {
    id: "ntrk_paper_dock",
    title: "Paper Dock",
    channel: "Glass Meadow",
    durationSec: 256,
    hue: 150,
    pattern: "bars",
    status: P.playable,
    description: "Soft keys over a paper-quiet beat.",
  },
  {
    id: "ntrk_kin_wires",
    title: "Kin Wires",
    channel: "Kin & Wire",
    durationSec: 198,
    hue: 195,
    pattern: "split",
    status: P.playable,
    description: "Two guitars, one shared room.",
  },
  {
    id: "ntrk_static_orchard",
    title: "Static Orchard",
    channel: "Static Orchard",
    durationSec: 241,
    hue: 92,
    pattern: "ring",
    status: P.playable,
    description: "Tape hiss and orchard night air.",
  },
  {
    id: "ntrk_veras_window",
    title: "Vera's Window",
    channel: "Vera Holt",
    durationSec: 176,
    hue: 340,
    pattern: "vinyl",
    status: P.playable,
    description: "Close vocal, open window, rain far off.",
  },
  {
    id: "ntrk_late_stations",
    title: "The Late Stations",
    channel: "The Late Stations",
    durationSec: 312,
    hue: 222,
    pattern: "bars",
    status: P.playable,
    description: "Empty platform, long sustain.",
  },
  {
    id: "ntrk_dust_chorus",
    title: "Dust Chorus",
    channel: "Dust Chorus",
    durationSec: 205,
    hue: 38,
    pattern: "arcs",
    status: P.playable,
    description: "Stacked hums, desert noon.",
  },
  {
    id: "ntrk_elm_circuit",
    title: "Elm Circuit",
    channel: "Elm Circuit",
    durationSec: 268,
    hue: 168,
    pattern: "split",
    status: P.playable,
    description: "Modular trees, slow blink.",
  },
  {
    id: "ntrk_june_radar",
    title: "June Radar",
    channel: "June Radar",
    durationSec: 191,
    hue: 48,
    pattern: "ring",
    status: P.playable,
    description: "Bright scan, summer grid.",
  },
  {
    id: "ntrk_hollow_pine",
    title: "Hollow Pine",
    channel: "Hollow Pine",
    durationSec: 224,
    hue: 130,
    pattern: "vinyl",
    status: P.playable,
    description: "Acoustic room, pine resin air.",
  },
  {
    id: "ntrk_mira_vale",
    title: "Mira Vale",
    channel: "Mira Vale",
    durationSec: 183,
    hue: 280,
    pattern: "arcs",
    status: P.playable,
    description: "Voice and a single held chord.",
  },
  {
    id: "ntrk_low_atlas_drift",
    title: "Low Atlas Drift",
    channel: "Low Atlas",
    durationSec: 348,
    hue: 200,
    pattern: "bars",
    status: P.playable,
    description: "Longform drift, no peak, no drop.",
  },
  {
    id: "ntrk_lantern_walk",
    title: "Lantern Walk",
    channel: "Paper Lantern",
    durationSec: 209,
    hue: 24,
    pattern: "ring",
    status: P.playable,
    description: "Footsteps and a paper glow.",
  },
  {
    id: "ntrk_harbor_night",
    title: "Harbor Night",
    channel: "Harbor Line",
    durationSec: 232,
    hue: 215,
    pattern: "vinyl",
    status: P.playable,
    description: "Foghorn interval, brushed drums.",
  },
  {
    id: "ntrk_north_room_two",
    title: "Second Desk",
    channel: "North Room",
    durationSec: 174,
    hue: 32,
    pattern: "split",
    status: P.playable,
    description: "The other lamp, same room.",
  },
  {
    id: "ntrk_quiet_hours",
    title: "Quiet Hours",
    channel: "Glass Meadow",
    durationSec: 401,
    hue: 160,
    pattern: "arcs",
    status: P.playable,
    description: "Four hundred seconds of unhurried air.",
  },
  {
    id: "ntrk_wire_garden",
    title: "Wire Garden",
    channel: "Kin & Wire",
    durationSec: 218,
    hue: 188,
    pattern: "bars",
    status: P.playable,
    description: "Plucked lines that almost talk.",
  },
  {
    id: "ntrk_orchard_rain",
    title: "Orchard Rain",
    channel: "Static Orchard",
    durationSec: 245,
    hue: 100,
    pattern: "vinyl",
    status: P.playable,
    description: "Wet leaves, delayed piano.",
  },
  {
    id: "ntrk_holt_line",
    title: "Holt Line",
    channel: "Vera Holt",
    durationSec: 193,
    hue: 350,
    pattern: "ring",
    status: P.playable,
    description: "A letter read once, then folded.",
  },
  {
    id: "ntrk_station_bell",
    title: "Station Bell",
    channel: "The Late Stations",
    durationSec: 227,
    hue: 228,
    pattern: "split",
    status: P.playable,
    description: "One bell, then the rails.",
  },
  {
    id: "ntrk_chorus_fade",
    title: "Chorus Fade",
    channel: "Dust Chorus",
    durationSec: 188,
    hue: 30,
    pattern: "arcs",
    status: P.playable,
    description: "Voices leaving the frame.",
  },
  {
    id: "ntrk_circuit_slow",
    title: "Circuit Slow",
    channel: "Elm Circuit",
    durationSec: 276,
    hue: 172,
    pattern: "bars",
    status: P.playable,
    description: "Clocked, but barely.",
  },
  {
    id: "ntrk_radar_bloom",
    title: "Radar Bloom",
    channel: "June Radar",
    durationSec: 201,
    hue: 52,
    pattern: "vinyl",
    status: P.playable,
    description: "A sweep that finds color.",
  },
  {
    id: "ntrk_pine_hollow",
    title: "Pine Hollow",
    channel: "Hollow Pine",
    durationSec: 239,
    hue: 124,
    pattern: "ring",
    status: P.playable,
    description: "Deeper in the same wood.",
  },
  {
    id: "ntrk_vale_light",
    title: "Vale Light",
    channel: "Mira Vale",
    durationSec: 164,
    hue: 265,
    pattern: "split",
    status: P.playable,
    description: "Short, bright, unfinished.",
  },
  {
    id: "ntrk_atlas_low",
    title: "Atlas Low",
    channel: "Low Atlas",
    durationSec: 291,
    hue: 204,
    pattern: "arcs",
    status: P.playable,
    description: "Bass almost under hearing.",
  },
  {
    id: "ntrk_lantern_two",
    title: "Second Lantern",
    channel: "Paper Lantern",
    durationSec: 215,
    hue: 18,
    pattern: "bars",
    status: P.playable,
    description: "The walk home, other street.",
  },
  {
    id: "ntrk_desk_lamp",
    title: "Desk Lamp",
    channel: "North Room",
    durationSec: 182,
    hue: 36,
    pattern: "vinyl",
    status: P.playable,
    description: "A small light, a long task.",
  },
  {
    id: "ntrk_weekend_mile",
    title: "Weekend Mile",
    channel: "Harbor Line",
    durationSec: 248,
    hue: 208,
    pattern: "ring",
    status: P.playable,
    description: "Open road, windows cracked.",
  },
  {
    id: "ntrk_field_notes",
    title: "Field Notes",
    channel: "Copper Saint",
    durationSec: 221,
    hue: 22,
    pattern: "split",
    status: P.playable,
    description: "Sketchbook songs, first take.",
  },
  {
    id: "ntrk_soft_grid",
    title: "Soft Grid",
    channel: "Elm Circuit",
    durationSec: 259,
    hue: 178,
    pattern: "bars",
    status: P.playable,
    description: "Quantized, then loosened.",
  },
  {
    id: "ntrk_night_parcel",
    title: "Night Parcel",
    channel: "Paper Lantern",
    durationSec: 196,
    hue: 16,
    pattern: "arcs",
    status: P.playable,
    description: "Something left at the door.",
  },
  {
    id: "ntrk_drive_glass",
    title: "Drive Glass",
    channel: "Harbor Line",
    durationSec: 237,
    hue: 200,
    pattern: "vinyl",
    status: P.playable,
    description: "Reflections on wet asphalt.",
  },
  {
    id: "ntrk_meadow_low",
    title: "Meadow Low",
    channel: "Glass Meadow",
    durationSec: 284,
    hue: 142,
    pattern: "ring",
    status: P.playable,
    description: "Grass at ankle height.",
  },
  {
    id: "ntrk_saint_copper",
    title: "Saint Copper",
    channel: "Copper Saint",
    durationSec: 208,
    hue: 26,
    pattern: "split",
    status: P.playable,
    description: "Brass and a wooden floor.",
  },
  {
    id: "ntrk_after_hours",
    title: "After Hours",
    channel: "Vera Holt",
    durationSec: 233,
    hue: 332,
    pattern: "bars",
    status: P.playable,
    description: "The bar is closed; the piano is not.",
  },
  {
    id: "ntrk_locked_cut",
    title: "Locked Cut",
    channel: "North Room",
    durationSec: 190,
    hue: 0,
    pattern: "bars",
    status: P.blocked,
    description: "Embedding is turned off for this mock item.",
  },
  {
    id: "ntrk_private_reel",
    title: "Private Reel",
    channel: "Harbor Line",
    durationSec: 205,
    hue: 220,
    pattern: "vinyl",
    status: P.gone,
    description: "This mock item is marked unavailable.",
  },
  {
    id: "ntrk_made_for_demo",
    title: "Catalog Demo",
    channel: "Needle Samples",
    durationSec: 142,
    hue: 240,
    pattern: "ring",
    status: P.playable,
    description: "A short demo cut used in empty-state tours.",
  },
];

const byId = new Map(MOCK_TRACKS.map((t) => [t.id, t]));

export function getTrack(id: string): Track | undefined {
  return byId.get(id);
}

export function getTracks(ids: string[]): Track[] {
  return ids.map((id) => byId.get(id)).filter((t): t is Track => Boolean(t));
}

export function searchCatalog(query: string): Track[] {
  const q = query.trim().toLowerCase();
  if (!q) return MOCK_TRACKS.filter((t) => t.status === "playable").slice(0, 12);
  return MOCK_TRACKS.filter((t) => {
    return (
      t.title.toLowerCase().includes(q) ||
      t.channel.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q)
    );
  });
}

export function totalDuration(ids: string[]): number {
  return ids.reduce((sum, id) => sum + (byId.get(id)?.durationSec ?? 0), 0);
}

export const CHANNELS = [...new Set(MOCK_TRACKS.map((t) => t.channel))].sort();
